### ISSUE TITLE
defaults.page.filter should not be obeyed

### ISSUE THREAD

**Issue by ghost** [radiant/radiant-sheets-extension#1]
Slightly tricky to fix this, since it's the hidden page part that's doing the filtering.

**Comment by saturnflyer** [comment]
can you explain this bug with some steps to reproduce it?

**Comment by spanner** [comment]
I can't reproduce it now. Sorry!

At the time I was getting textile formatting of stylesheets if defaults.page.filter was set and the sheet had no filter of its own. It must have been a side effect.
