### ISSUE TITLE
(really) long files are clipped without warning

### ISSUE THREAD

**Issue by jomz** [radiant/radiant-sheets-extension#10]
I suppose this depends on the database solution being used, but I run into this with MySQL;
If I upload for example jquery-1.6.2.min.js, the contents are clipped, and I only found out because I got an error.

This also happens when I paste the JS into the Sheets page myself, so it has nothing to do with the upload process;
I noticed it doesn't allow uploads larger than 256kB, but jquery-1.6.2.min.js is only 94kB and silently fails..

**Comment by jomz** [comment]
I think the best way to tackle this would be to update Page's content column to :limit => 16777215
@saturnflyer I'd add a migration to Radiant for this if you concur.

**Comment by saturnflyer** [comment]
Strange. Where do you get the number 16777215? 

I'd hate to limit the column if it's just a database configuration issue.
Can this be solved with local configuration to your database?

**Comment by jomz** [comment]
from http://stackoverflow.com/questions/4443477/rails-3-migration-with-longtext
the default for text is 65535 or 64kB

**Comment by saturnflyer** [comment]
What do you think about checking for the database type? If this doesn't occur in Postgres or others, then I'd avoid the setting. Some pseudo code

```
if ActiveRecord::Base.connection.adapter_name =~ /mysql/i
  # set the limit
else
  # do the normal thing
end
```

**Comment by jomz** [comment]
Postgre does indeed seem to make TEXT columns unlimited, same for SQLite.
Which other databases should I check?

**Comment by saturnflyer** [comment]
Perhaps @acangiano can weigh in on DB2. Don't know about MS SQL Server.

**Comment by acangiano** [comment]
The Rails adapter for DB2 has a 1 MB default for text columns. However, the actual DB2 9.7 limit for CLOB (so text columns) fields is 2,147,483,647 Bytes. So the following would give you a 2 GB limit:

``` ruby
t.text body, :limit =>  2147483647
```

See here for more info on DB2's SQL limits: http://publib.boulder.ibm.com/infocenter/db2luw/v9r7/index.jsp?topic=%2Fcom.ibm.db2.luw.sql.ref.doc%2Fdoc%2Fr0001029.html

**Comment by jomz** [comment]
MS SQL appears to have the same default limit as MySQL, so the migration would have to be run for those 2.
2 GB is probably serious overkill; so far the limit was 64kB, and AFAIK not many people have ran into this issue yet.
I'd go with 1MB, that should be spatious enough for any un-minified JS or CSS file ...

**Comment by jomz** [comment]
Fixed by https://github.com/radiant/radiant/commit/fece2b17d31092189863d97386e0b7045705477e
