### ISSUE TITLE
as="link" not working?

### ISSUE THREAD

**Issue by catmando** [radiant/radiant-sheets-extension#3]
for example <r:stylesheet name="foo.css" as="link"/>
generates <link href="/css/foo.css?1294945640" type="text/css" rel="stylesheet">
as expected
however the server returns Page Not Found

This is on a fairly recent install of edge radiant (last week) , and only :sheets, and :assets enabled.

BTW as="inline" seems to work.

Anything I can try to help debug or get this going, let me know. 

Thanks

**Comment by saturnflyer** [comment]
Thanks for reporting this. I'm unable to recreate this problem. Is this still a problem?

**Comment by catmando** [comment]
It does appear fixed now.  Thanks
