### ISSUE TITLE
threading glitches on tree creation

### ISSUE THREAD

**Issue by ghost** [radiant/radiant-sheets-extension#4]
1. bootstrap a new site
2. vendor edge radiant
3. pull the latest sheets
4. navigate to stylesheets list
5. press 'new stylesheet'

I get errors like this:

```
ActiveRecord::AssociationTypeMismatch in Admin/stylesController#new
User(#2201276360) expected, got User(#2201699120)
```

I believe the problem is to do with thread-safety in Admin::SheetResourceController.create_root but I haven't investigated very far. Some stack:

```
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations/association_proxy.rb:259:in `raise_on_type_mismatch'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:22:in `replace'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations.rb:1287:in `created_by='
/private/var/www/rspca/vendor/radiant/app/models/user_action_observer.rb:13:in `before_create'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/observer.rb:171:in `send'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/observer.rb:171:in `update'
/opt/local/lib/ruby/1.8/observer.rb:185:in `notify_observers'
/opt/local/lib/ruby/1.8/observer.rb:184:in `each'
/opt/local/lib/ruby/1.8/observer.rb:184:in `notify_observers'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:357:in `notify'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:350:in `callback'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:265:in `create'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/base.rb:2915:in `create_or_update_without_callbacks'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:250:in `create_or_update'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/base.rb:2573:in `save_without_validation'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/validations.rb:1090:in `save_without_dirty'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/dirty.rb:79:in `save_without_transactions'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:229:in `send'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:182:in `transaction'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/private/var/www/rspca/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
/private/var/www/rspca/vendor/radiant/vendor/extensions/sheets/app/controllers/admin/sheet_resource_controller.rb:48:in `create_root'
```

and by the way this is with nginx/passenger on OS X in dev mode and restarting the passenger process makes the problem go away.

**Comment by saturnflyer** [comment]
I've actually seen this too. Thanks for making the issue.

**Comment by Swartz** [comment]
Running latest Radiant edge on FreeBSD in dev mode, ruby v1.8.7, Rails 2.3.8, Apache with mod_passenger v3.0.7.
Seeing this as well. It happened when I hit  either "New Stylesheet" or "New JavaScript".
Restarted the app as described about, the problem with "New JavaScript" went away, but "New Stylesheet" still causes the above error.

**Comment by saturnflyer** [comment]
With the latest code, I'm unable to recreate this problem. Could either of you verify this?

**Comment by spanner** [comment]
Yup. All fixed. The homepage catch is nice too, but I didn't realise the first time round that I had to publish that page too.

**Comment by Swartz** [comment]
Just finally got around to testing out latest Radiant. Sadly I still see the same issue with current edge.
Except this time, after restarting the app, "New Stylesheet" works, but "New Javascript" errors out.

Apache v2.2.16 with passenger v3.0.7

`> ruby -v
ruby 1.8.7 (2009-12-24 patchlevel 248) [i386-freebsd7]`

`ActiveRecord::AssociationTypeMismatch in Admin/scriptsController#new 
User(#365008240) expected, got User(#365128550)`

Full trace:
`/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations/association_proxy.rb:259:in `raise_on_type_mismatch'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:22:in `replace'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations.rb:1287:in `created_by='
/home/swartz/play/radiant_edge/vendor/radiant/app/models/user_action_observer.rb:19:in `before_create'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/observer.rb:171:in `send'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/observer.rb:171:in `update'
/usr/local/lib/ruby/1.8/observer.rb:185:in `notify_observers'
/usr/local/lib/ruby/1.8/observer.rb:184:in `each'
/usr/local/lib/ruby/1.8/observer.rb:184:in `notify_observers'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:357:in `notify'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:350:in `callback'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:265:in `create'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/base.rb:2927:in `create_or_update_without_callbacks'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:250:in `create_or_update'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/base.rb:2577:in `save_without_validation'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/validations.rb:1090:in `save_without_dirty'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/dirty.rb:79:in `save_without_transactions'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:229:in `send'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:182:in `transaction'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/extensions/sheets/app/models/sheet.rb:23:in `create_root'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/extensions/sheets/app/controllers/admin/sheet_resource_controller.rb:44:in `create_root'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `send'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:225:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:629:in `run_before_filters'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/local/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/flash.rb:151:in `perform_action'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `send'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `process_without_filters'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process_without_compass'
/usr/local/lib/ruby/gems/1.8/gems/compass-0.11.1/lib/compass/app_integration/rails/actionpack2/action_controller.rb:7:in `process'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/base.rb:391:in `process'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/base.rb:386:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb:438:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:87:in `dispatch'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:121:in `_call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:130
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/query_cache.rb:9:in `cache'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/query_cache.rb:28:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/usr/local/lib/ruby/gems/1.8/gems/sass-3.1.2/lib/sass/plugin/rack.rb:54:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/string_coercion.rb:25:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/head.rb:9:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/methodoverride.rb:24:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/params_parser.rb:15:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/session/cookie_store.rb:99:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/failsafe.rb:26:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/lock.rb:11:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/lock.rb:11:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/lock.rb:11:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:114:in `call'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/reloader.rb:34:in `run'
/home/swartz/play/radiant_edge/vendor/radiant/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:108:in `call'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/utils.rb:479:in `safe_fork'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:180:in `start'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/helper-scripts/passenger-spawn-server:99`
